name: TestCore
version: '${project.version}'
main: io.paper.testcore.Main
commands:
  gmc:
    description: gmc
  gms:
    description: gms
  kit:
    description: give kit
  gapple:
    description: gapple
  blocchi:
    description: blocchi
  setspawn:
    description: setspawn
